version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/utils-common
    environment:
      GRADLE_OPTS: -Xmx3200m
      artifact_dir: "artifacts"
    steps:
      - checkout
      - run:
          name: Setup GPG and Gradle Props
          command: |
            sudo apt-get install gettext gnupg2 -y
            curl ${GPG_OUT} -o private.key && gpg2 --allow-secret-key-import --import private.key
            gpg2 --export-secret-key ${GPG_KEYID} > secring.gpg
            envsubst < "gradle.properties.tpl" > "gradle.properties"
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run:
          name: Gradle Check
          command: ./gradlew --warning-mode=none -PprojVersion=latest check
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Collect Test Artifacts
          command: |
            mkdir -p ${artifact_dir}/reports/ ${artifact_dir}/output/
            cp -r build/reports ${artifact_dir}/
          when: always
      - store_artifacts:
          path: artifacts
      - run:
          name: Upload Code Coverage
          command: 'bash <(curl -s https://codecov.io/bash) -t 75db8c6b-3439-45de-9d6f-f3da60f59e9d'

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/utils-common
    environment:
      GRADLE_OPTS: -Xmx3200m
      artifact_dir: "artifacts"
    steps:
      - checkout
      - run:
          name: Setup GPG and Gradle Props
          command: |
            sudo apt-get install gettext gnupg2 -y
            curl ${GPG_OUT} -o private.key && gpg2 --allow-secret-key-import --import private.key
            gpg2 --export-secret-key ${GPG_KEYID} > secring.gpg
            envsubst < "gradle.properties.tpl" > "gradle.properties"
      - run:
          name: Gradle Deploy
          command: |
            ./gradlew --warning-mode=none -PprojVersion=${CIRCLE_TAG:1} uploadArchives

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+).*/
            branches:
              ignore: /.*/